id = "fastapi-lsp"
name = "fastapi-lsp"
description = "Language server for FastAPI and Starlette"
version = "0.1.1"
schema_version = 1
authors = ["Alex Oleshkevich <alex.oleshkevich@gmail.com>"]
repository = "https://github.com/alex-oleshkevich/fastapi-lsp"

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.fastapi-lsp]
name = "fastapi-lsp"
languages = ["Python", "HTML", "Jinja2"]

[language_servers.fastapi-lsp.language_ids]
"Python" = "python"
"HTML" = "html"
"Jinja2" = "jinja2"
